#!/bin/bash
# =============================================================================
# REFERENCIA RÁPIDA: SISTEMA DE JUECES - COMANDOS Y ACCESOS ÚTILES
# =============================================================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                  REFERENCIA RÁPIDA: JUECES                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "🌐 ACCESOS RÁPIDOS EN NAVEGADOR:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Admin:"
echo "  • Panel de Jueces:      http://localhost/admin/jueces"
echo "  • Crear Juez:           http://localhost/admin/jueces/crear"
echo "  • Asignar Eventos:      http://localhost/admin/jueces/{id}/asignar-eventos"
echo ""
echo "Juez:"
echo "  • Panel Principal:      http://localhost/juez/panel"
echo "  • Historial:            http://localhost/juez/constancias"
echo ""

echo "📂 ARCHIVOS PRINCIPALES:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Vistas:"
echo "  • resources/views/admin/jueces/index.blade.php (lista)"
echo "  • resources/views/admin/jueces/create.blade.php (crear)"
echo "  • resources/views/admin/jueces/credentials.blade.php (credenciales)"
echo "  • resources/views/admin/jueces/asignar.blade.php (asignar eventos)"
echo "  • resources/views/juez/panel.blade.php (panel juez)"
echo "  • resources/views/juez/constancias.blade.php (historial)"
echo ""
echo "Modelos:"
echo "  • app/Models/Usuario.php (esJuez, eventosAsignados)"
echo "  • app/Models/Evento.php (jueces)"
echo "  • app/Models/Equipo.php (jueces, juez)"
echo ""
echo "Controladores:"
echo "  • app/Http/Controllers/AdminController.php (5 métodos jueces)"
echo "  • app/Http/Controllers/JuezController.php (panel, constancias)"
echo ""

echo "🔧 COMANDOS ÚTILES:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Limpiar caché de vistas:"
echo "  $ php artisan view:clear"
echo ""
echo "Ver rutas registradas:"
echo "  $ php artisan route:list | grep juez"
echo ""
echo "Estado de migraciones:"
echo "  $ php artisan migrate:status | grep juez"
echo ""
echo "Validar sistema:"
echo "  $ php test_juez_sync.php"
echo ""
echo "Acceder a Tinker (shell interactivo):"
echo "  $ php artisan tinker"
echo "  > \\App\\Models\\Usuario::jueces()->count()"
echo ""

echo "🗄️  ESTRUCTURA DE BASE DE DATOS:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Tabla: usuarios"
echo "  • tipo: ENUM('administrador', 'participante', 'juez')"
echo ""
echo "Tabla: juez_evento (Pivot)"
echo "  • usuario_id (FK → usuarios.id)"
echo "  • evento_id (FK → eventos.id_evento)"
echo "  • created_at, updated_at"
echo "  • Constraint UNIQUE: (usuario_id, evento_id)"
echo ""

echo "🧪 FLUJO DE PRUEBA:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "1. Crear Juez:"
echo "   • Ir a: /admin/jueces/crear"
echo "   • Llenar: nombre, apellidos, email"
echo "   • Guardar → Ver credenciales"
echo ""
echo "2. Asignar Eventos:"
echo "   • Ir a: /admin/jueces → Clic 'Asignar'"
echo "   • Seleccionar eventos (checkboxes)"
echo "   • Guardar → Redireccionar a /admin/jueces"
echo ""
echo "3. Acceso del Juez:"
echo "   • Logout"
echo "   • Login con credenciales del juez"
echo "   • Auto-redirecciona a /juez/panel"
echo "   • Ver eventos asignados"
echo ""

echo "🔑 CREDENCIALES DE PRUEBA:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "Admin (si existe):"
echo "  • Email: admin@test.com"
echo "  • Password: password"
echo ""
echo "Nuevo Juez:"
echo "  • Se genera contraseña aleatoria de 10 caracteres"
echo "  • Se muestra en pantalla post-creación"
echo "  • Se envía por email"
echo ""

echo "📚 DOCUMENTACIÓN:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  • ENTREGA_FINAL.md - Resumen ejecutivo"
echo "  • ARQUITECTURA_JUEZ_ASIGNACION.md - Técnico"
echo "  • TEST_JUEZ_ASIGNACION.md - Guía de pruebas"
echo "  • CHECKLIST_IMPLEMENTACION.md - Estado del proyecto"
echo "  • RESUMEN_EJECUTIVO_JUECES.md - Overview"
echo ""

echo "🔐 SEGURIDAD:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  • Solo admin puede crear jueces"
echo "  • Solo admin puede asignar eventos"
echo "  • Solo juez loggeado puede acceder a /juez/panel"
echo "  • Validación de permisos en todas las rutas"
echo "  • Contraseñas hasheadas con Hash::make()"
echo ""

echo "💡 TIPS:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  • Al crear juez, copiar credenciales inmediatamente"
echo "  • La redirección de juez es automática después de login"
echo "  • Desasignar eventos es tan simple como desmarcar checkboxes"
echo "  • El contador de asignaciones se actualiza en tiempo real"
echo "  • Cada juez puede tener múltiples eventos asignados"
echo ""

echo "❓ PROBLEMAS COMUNES:"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "  ❌ Vista no carga → php artisan view:clear"
echo "  ❌ Checkboxes no marcados → Validar eventosAsignados()"
echo "  ❌ Email no se envía → Verificar config/mail.php"
echo "  ❌ Juez no ve eventos → Verificar relación eventosAsignados()"
echo ""

echo "═════════════════════════════════════════════════════════════════"
echo "✅ Sistema listo para usar. ¡Comienza con /admin/jueces!"
echo "═════════════════════════════════════════════════════════════════"
echo ""
